# Generated by Django 4.2.6 on 2023-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='total_like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
