# Generated by Django 4.2.6 on 2023-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
